### PR TITLE
Add ability to set a background color for indicator container

### PR DESCRIPTION
**Pull request by lmbcosta**
Hello👋

One of the simple customization that is missing is the ability to give a background color for indicator container in ```TMBarView```

### CODE REVIEW

**Comment by javadmahmoodi** [comment]
Hello. How can I set the tab titles to fill the entire width of the phone screen and the tab titles to be read completely. I am unable to do this and I ask you for help. Thank you
🙏🏻🙏🏻🌹

image

**Comment by lmbcosta** [comment]
Hi @javadmahmoodi👋

You can use these bar layout properties: 
```
layout.alignment = .centerDistributed
layout.contentMode = .fit 
```

So if you are subclassing `TabmanViewController` just follow this example:

```
class YourViewController: TabmanViewController {
  let bar: TMBarView = {
    let b = TMBar.ButtonBar()
    // bar customization
    b.layout.alignment = .centerDistributed
    b.layout.contentMode = .fit 
    return b
  }()

  override func viewDidLoad() {
    super.viewDidLoad()
    dataSource = self
    addBar(bar, dataSource: self, at: .top)
  }
}
```

I hope it helps 🙂

**Comment by javadmahmoodi** [comment]
Hello.  I did exactly like you but the result was like the picture below.  
How can all tab titles fill the phone screen full and at the same time?  
If it is scrolling but all titles are legible, it is also good.

image

**Comment by javadmahmoodi** [comment]
> Hi @javadmahmoodi👋
> 
> 
> 
> You can use these bar layout properties: 
> 
> ```
> 
> layout.alignment = .centerDistributed
> 
> layout.contentMode = .fit 
> 
> ```
> 
> 
> 
> So if you are subclassing `TabmanViewController` just follow this example:
> 
> 
> 
> ```
> 
> class YourViewController: TabmanViewController {
> 
>   let bar: TMBarView = {
> 
>     let b = TMBar.ButtonBar()
> 
>     // bar customization
> 
>     b.layout.alignment = .centerDistributed
> 
>     b.layout.contentMode = .fit 
> 
>     return b
> 
>   }()
> 
> 
> 
>   override func viewDidLoad() {
> 
>     super.viewDidLoad()
> 
>     dataSource = self
> 
>     addBar(bar, dataSource: self, at: .top)
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> I hope it helps 🙂

Hello.  
I did exactly like you but the result was like the picture below.  
How can all tab titles fill the phone screen full and at the same time?  
If it is scrolling but all titles are legible, it is also good.

image

**Comment by lmbcosta** [comment]
Hi @javadmahmoodi👋

_How can all tab titles fill the phone screen full and at the same time?_
Fill the phone and preserve correct with for titles is not possible. For that, your content should be scrollable to fit on the available width. For that consider the below properties:
```
let bar = TMBar.ButtonBar()
bar.layout.contentMode = .intrinsic
bar.layout.alignment = .centerDistributed
```

Make sure that `bar.scrollMode` property is **not** `.none`. Play with other options (`interactive` and `swipe`) to fit your needs.

**Pull request closed without merging**
